//! LLM → Deterministic Function Pipeline.
//!
//! When an LLM handles a query that could have a closed-form answer,
//! the orchestrator can tag it. The Dreamer picks these up and produces
//! typed FunctionProposals. A human reviews, approves, and a Coder agent
//! writes the Rust implementation. Once merged, that query type costs
//! zero tokens forever.
//!
//! ## The asymptote
//!
//! Over time the deterministic library grows and the LLM fires less
//! often for routine computation. The LLM's remaining work becomes
//! genuinely hard: judgment, creativity, ambiguous context.
//! That's the goal — push the LLM toward what only it can do.

use std::collections::HashMap;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ═══════════════════════════════════════
// FunctionProposal — typed IR output from the LLM/Dreamer
// ═══════════════════════════════════════

/// A proposal for a new deterministic function, generated by an LLM
/// after identifying a repeated closed-form pattern.
///
/// LLMs produce this. Humans review it. Coder agents implement it.
/// The LLM never writes the final Rust — it proposes the shape.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionProposal {
    pub id: String,
    pub name: String,
    pub module: FunctionModule,
    pub description: String,
    pub signature: ProposedSignature,
    pub implementation_hint: String,
    pub example_queries: Vec<String>,
    pub supporting_episodes: Vec<String>,
    pub confidence: f64,
    pub proposed_at: DateTime<Utc>,
    pub status: ProposalStatus,
    pub reviewer_notes: Option<String>,
}

/// Which deterministic module this function belongs to.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum FunctionModule {
    Music,
    Finance,
    Data,
    Time,
    Text,
    Code,
    Geo,
    Universal,
    New(String),  // for completely new module proposals
}

impl FunctionModule {
    #[must_use]
    pub fn module_path(&self) -> String {
        match self {
            Self::Music    => "crates/common/src/det_music.rs".to_string(),
            Self::Finance  => "crates/common/src/det_finance.rs".to_string(),
            Self::Data     => "crates/common/src/det_data.rs".to_string(),
            Self::Time     => "crates/common/src/det_time.rs".to_string(),
            Self::Text     => "crates/common/src/det_text.rs".to_string(),
            Self::Code     => "crates/common/src/det_code.rs".to_string(),
            Self::Geo      => "crates/common/src/det_geo.rs".to_string(),
            Self::Universal => "crates/common/src/deterministic.rs".to_string(),
            Self::New(n)   => format!("crates/common/src/det_{}.rs", n.to_lowercase()),
        }
    }
}

/// The proposed function signature (Rust-style).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProposedSignature {
    pub fn_name: String,
    pub params: Vec<ParamSpec>,
    pub return_type: String,
    pub is_pure: bool,       // always true for deterministic functions
    pub is_fallible: bool,   // should it return Result<T, String>?
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParamSpec {
    pub name: String,
    pub r#type: String,
    pub description: String,
}

/// The lifecycle of a function proposal.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProposalStatus {
    /// Newly proposed, awaiting review.
    Pending,
    /// Under human review.
    UnderReview,
    /// Approved — Coder agent has been dispatched.
    Approved,
    /// Rejected — won't be implemented (reason in reviewer_notes).
    Rejected,
    /// Implemented and merged.
    Implemented { merged_at: String },
    /// Duplicate of an existing function.
    Duplicate { existing_fn: String },
}

/// Orchestrator dispatch task generated when a proposal is approved.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodingTask {
    pub task_id: String,
    pub proposal_id: String,
    pub agent_role: String,   // "coder"
    pub instructions: String,
    pub target_file: String,
    pub verification: String,
    pub priority: TaskPriority,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TaskPriority { High, Medium, Low }

// ═══════════════════════════════════════
// Proposal Queue (stored on disk)
// ═══════════════════════════════════════

/// The queue of pending/approved function proposals.
pub struct ProposalQueue {
    proposals: Vec<FunctionProposal>,
    storage_path: std::path::PathBuf,
}

impl ProposalQueue {
    #[must_use]
    pub fn new(storage_path: impl AsRef<std::path::Path>) -> Self {
        Self {
            proposals: Vec::new(),
            storage_path: storage_path.as_ref().to_path_buf(),
        }
    }

    /// Add a new proposal.
    pub fn submit(&mut self, proposal: FunctionProposal) -> String {
        let id = proposal.id.clone();
        self.proposals.push(proposal);
        id
    }

    /// Get pending proposals.
    #[must_use]
    pub fn pending(&self) -> Vec<&FunctionProposal> {
        self.proposals.iter()
            .filter(|p| p.status == ProposalStatus::Pending)
            .collect()
    }

    /// Approve a proposal — returns the generated CodingTask.
    pub fn approve(&mut self, id: &str, notes: Option<String>) -> Option<CodingTask> {
        let proposal = self.proposals.iter_mut().find(|p| p.id == id)?;
        proposal.status = ProposalStatus::Approved;
        proposal.reviewer_notes = notes;
        Some(generate_coding_task(proposal))
    }

    /// Reject a proposal.
    pub fn reject(&mut self, id: &str, reason: &str) {
        if let Some(p) = self.proposals.iter_mut().find(|p| p.id == id) {
            p.status = ProposalStatus::Rejected;
            p.reviewer_notes = Some(reason.to_string());
        }
    }

    /// Mark as implemented.
    pub fn mark_implemented(&mut self, id: &str, merged_at: &str) {
        if let Some(p) = self.proposals.iter_mut().find(|p| p.id == id) {
            p.status = ProposalStatus::Implemented { merged_at: merged_at.to_string() };
        }
    }

    /// Stats for observability.
    #[must_use]
    pub fn stats(&self) -> ProposalStats {
        let mut stats = ProposalStats::default();
        for p in &self.proposals {
            match &p.status {
                ProposalStatus::Pending        => stats.pending += 1,
                ProposalStatus::Approved       => stats.approved += 1,
                ProposalStatus::Rejected       => stats.rejected += 1,
                ProposalStatus::Implemented{..}=> stats.implemented += 1,
                ProposalStatus::Duplicate{..}  => stats.duplicates += 1,
                ProposalStatus::UnderReview    => stats.under_review += 1,
            }
        }
        stats
    }

    /// Save to disk (JSON).
    pub fn save(&self) -> Result<(), String> {
        if let Some(parent) = self.storage_path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        let json = serde_json::to_string_pretty(&self.proposals)
            .map_err(|e| e.to_string())?;
        std::fs::write(&self.storage_path, json).map_err(|e| e.to_string())
    }

    /// Load from disk.
    pub fn load(&mut self) -> Result<usize, String> {
        if !self.storage_path.exists() { return Ok(0); }
        let json = std::fs::read_to_string(&self.storage_path)
            .map_err(|e| e.to_string())?;
        self.proposals = serde_json::from_str(&json).map_err(|e| e.to_string())?;
        Ok(self.proposals.len())
    }

    pub fn len(&self) -> usize { self.proposals.len() }
    pub fn is_empty(&self) -> bool { self.proposals.is_empty() }
}

#[derive(Debug, Clone, Default, Serialize)]
pub struct ProposalStats {
    pub pending: usize,
    pub under_review: usize,
    pub approved: usize,
    pub rejected: usize,
    pub implemented: usize,
    pub duplicates: usize,
}

// ═══════════════════════════════════════
// Formalizeability Tagger
// ═══════════════════════════════════════

/// Signals that suggest an LLM response could have been deterministic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FormalizabilitySignal {
    pub episode_id: String,
    pub query_preview: String,
    pub signal_type: SignalType,
    pub suggested_module: FunctionModule,
    pub confidence: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum SignalType {
    /// Response is a number or formula result.
    NumericResult,
    /// Response is a lookup (table-driven, finite domain).
    LookupResult,
    /// Same query pattern appeared in multiple sessions.
    RepeatedPattern,
    /// Response matches a known algorithm.
    AlgorithmicPattern,
    /// User rephrased a question that was answered before.
    RephraseOfPrior,
}

/// Tag an LLM response for formalizability.
#[must_use]
pub fn tag_formalizability(query: &str, response: &str, episode_id: &str) -> Vec<FormalizabilitySignal> {
    let mut signals = Vec::new();
    let q = query.to_lowercase();
    let r = response.to_lowercase();

    // Numeric result signal
    let numeric_words = ["how many", "calculate", "what is", "convert",
                         "how much", "distance", "percent", "ratio", "rate"];
    if numeric_words.iter().any(|kw| q.contains(kw)) {
        // Check if response contains a number
        if r.chars().any(|c| c.is_ascii_digit()) {
            let module = infer_module_from_query(&q);
            signals.push(FormalizabilitySignal {
                episode_id: episode_id.to_string(),
                query_preview: query.chars().take(100).collect(),
                signal_type: SignalType::NumericResult,
                confidence: 0.75,
                suggested_module: module,
            });
        }
    }

    // Lookup result signal — short, categorical responses
    if r.split_whitespace().count() < 10
        && !r.contains("because") && !r.contains("however") {
        let module = infer_module_from_query(&q);
        if module != FunctionModule::Universal {
            signals.push(FormalizabilitySignal {
                episode_id: episode_id.to_string(),
                query_preview: query.chars().take(100).collect(),
                signal_type: SignalType::LookupResult,
                confidence: 0.65,
                suggested_module: module,
            });
        }
    }

    signals
}

fn infer_module_from_query(q: &str) -> FunctionModule {
    if q.contains("bpm") || q.contains("scale") || q.contains("chord")
        || q.contains("hz") || q.contains("note") || q.contains("beat")
        || q.contains("verse") || q.contains("lyric") { return FunctionModule::Music; }
    if q.contains("stock") || q.contains("option") || q.contains("price")
        || q.contains("return") || q.contains("volatility") || q.contains("sharpe")
        { return FunctionModule::Finance; }
    if q.contains("mean") || q.contains("median") || q.contains("average")
        || q.contains("percentile") || q.contains("correlation")
        { return FunctionModule::Data; }
    if q.contains("date") || q.contains("time") || q.contains("timezone")
        || q.contains("days") || q.contains("month") || q.contains("year")
        { return FunctionModule::Time; }
    if q.contains("word") || q.contains("text") || q.contains("sentence")
        || q.contains("syllable") || q.contains("readab")
        { return FunctionModule::Text; }
    if q.contains("version") || q.contains("semver") || q.contains("hash")
        || q.contains("base64") || q.contains("hex") || q.contains("encode")
        { return FunctionModule::Code; }
    if q.contains("distance") || q.contains("latitude") || q.contains("longitude")
        || q.contains("miles") || q.contains("km") && q.contains("coord")
        { return FunctionModule::Geo; }
    FunctionModule::Universal
}

// ═══════════════════════════════════════
// OperatorRuleProposal
// ═══════════════════════════════════════

/// A proposal for a TOML operator rule (lower friction than a full Rust function).
///
/// Proposed by the Dreamer when it detects repeatable patterns that can be
/// expressed as a deterministic rule rather than compiled Rust.  Operators
/// review, optionally edit, and flip `approved = true` in the generated
/// `rules.toml` to activate the rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OperatorRuleProposal {
    /// Unique proposal identifier, e.g. `"orp-3f2a"".
    pub id: String,
    /// The rule `id` field this will produce in `rules.toml`.
    pub rule_id: String,
    /// Human-readable description of the proposed rule.
    pub description: String,
    /// Keywords that should trigger this rule (Option A routing).
    pub trigger_keywords: Vec<String>,
    /// Semantic description for embedding-based routing (Option C).
    pub semantic_hint: Option<String>,
    /// The proposed formula type.
    pub formula: ProposedFormula,
    /// Estimated confidence (0.0–1.0).
    pub confidence: f64,
    /// IDs of the episodic traces that motivated this proposal.
    pub supporting_episodes: Vec<String>,
    /// Example input queries the rule should handle.
    pub example_inputs: Vec<String>,
    /// Expected outputs for the corresponding example inputs.
    pub example_outputs: Vec<String>,
    /// When this proposal was generated.
    pub proposed_at: DateTime<Utc>,
    /// Lifecycle status — starts as Pending, operator sets to Approved.
    pub status: ProposalStatus,
}

/// The proposed formula type — what kind of deterministic rule this should be.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProposedFormula {
    /// Always return a fixed string.
    Static { response: String },
    /// Arithmetic expression with variable substitution.
    Arithmetic { expr: String, variables: Vec<String> },
    /// Lookup table as (key, value) pairs (order-preserving).
    Lookup { pairs: Vec<(String, String)> },
    /// Weighted keyword scoring.
    WeightedScore { keyword_weights: Vec<(String, f64)> },
    /// String template with named slots.
    Template { template: String, slots: Vec<String> },
}

// ═══════════════════════════════════════
// CodingTask generation
// ═══════════════════════════════════════

fn generate_coding_task(proposal: &FunctionProposal) -> CodingTask {
    let instructions = format!(
        "Implement the deterministic function `{}` in `{}`.\n\
         \n\
         Description: {}\n\
         \n\
         Proposed signature:\n\
         ```rust\n\
         pub fn {}({}) -> {}\n\
         ```\n\
         \n\
         Implementation hint: {}\n\
         \n\
         Example queries this function should answer:\n\
         {}\n\
         \n\
         Rules:\n\
         - Function must be pure (no side effects, no I/O, no LLM calls)\n\
         - Add #[must_use] if it returns a value\n\
         - Add comprehensive unit tests\n\
         - Follow the existing style in the target file\n\
         - Register in try_deterministic_resolution() if it matches natural language",
        proposal.signature.fn_name,
        proposal.module.module_path(),
        proposal.description,
        proposal.signature.fn_name,
        proposal.signature.params.iter()
            .map(|p| format!("{}: {}", p.name, p.r#type))
            .collect::<Vec<_>>().join(", "),
        proposal.signature.return_type,
        proposal.implementation_hint,
        proposal.example_queries.iter()
            .map(|q| format!("- \"{q}\""))
            .collect::<Vec<_>>().join("\n"),
    );

    CodingTask {
        task_id: format!("OD-{}", uuid_short()),
        proposal_id: proposal.id.clone(),
        agent_role: "coder".to_string(),
        instructions,
        target_file: proposal.module.module_path(),
        verification: format!(
            "cargo test -p nstn-common {} -- --nocapture",
            proposal.signature.fn_name
        ),
        priority: if proposal.confidence >= 0.8 { TaskPriority::High }
                  else if proposal.confidence >= 0.5 { TaskPriority::Medium }
                  else { TaskPriority::Low },
    }
}

fn uuid_short() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let ts = SystemTime::now().duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis()).unwrap_or(0);
    format!("{:X}", ts & 0xFFFFFF)
}

// ═══════════════════════════════════════
// Tests
// ═══════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn sample_proposal(id: &str) -> FunctionProposal {
        FunctionProposal {
            id: id.to_string(),
            name: "options_delta".to_string(),
            module: FunctionModule::Finance,
            description: "Calculate option delta for a call or put".to_string(),
            signature: ProposedSignature {
                fn_name: "option_delta".to_string(),
                params: vec![
                    ParamSpec { name: "s".to_string(), r#type: "f64".to_string(), description: "spot price".to_string() },
                    ParamSpec { name: "k".to_string(), r#type: "f64".to_string(), description: "strike".to_string() },
                    ParamSpec { name: "option_type".to_string(), r#type: "&str".to_string(), description: "call or put".to_string() },
                ],
                return_type: "f64".to_string(),
                is_pure: true,
                is_fallible: false,
            },
            implementation_hint: "Use normal_cdf(d1) for call, normal_cdf(d1) - 1 for put".to_string(),
            example_queries: vec![
                "what is the delta of a call option at the money".to_string(),
            ],
            supporting_episodes: vec!["e_001".to_string()],
            confidence: 0.85,
            proposed_at: Utc::now(),
            status: ProposalStatus::Pending,
            reviewer_notes: None,
        }
    }

    #[test]
    fn proposal_queue_submit_and_retrieve() {
        let tmp = TempDir::new().unwrap();
        let mut queue = ProposalQueue::new(tmp.path().join("proposals.json"));
        let id = queue.submit(sample_proposal("p001"));
        assert_eq!(id, "p001");
        assert_eq!(queue.pending().len(), 1);
    }

    #[test]
    fn proposal_approve_generates_coding_task() {
        let tmp = TempDir::new().unwrap();
        let mut queue = ProposalQueue::new(tmp.path().join("proposals.json"));
        queue.submit(sample_proposal("p002"));
        let task = queue.approve("p002", Some("looks good".to_string())).unwrap();
        assert_eq!(task.agent_role, "coder");
        assert!(task.instructions.contains("option_delta"));
        assert!(task.target_file.contains("det_finance"));
    }

    #[test]
    fn proposal_queue_save_and_load() {
        let tmp = TempDir::new().unwrap();
        let path = tmp.path().join("proposals.json");
        let mut queue = ProposalQueue::new(&path);
        queue.submit(sample_proposal("p003"));
        queue.save().unwrap();
        let mut queue2 = ProposalQueue::new(&path);
        let count = queue2.load().unwrap();
        assert_eq!(count, 1);
        assert_eq!(queue2.pending().len(), 1);
    }

    #[test]
    fn stats_tracking() {
        let tmp = TempDir::new().unwrap();
        let mut queue = ProposalQueue::new(tmp.path().join("proposals.json"));
        queue.submit(sample_proposal("p004"));
        queue.submit(sample_proposal("p005"));
        queue.approve("p004", None);
        queue.reject("p005", "already covered by det_finance::option_delta_call");
        let stats = queue.stats();
        assert_eq!(stats.approved, 1);
        assert_eq!(stats.rejected, 1);
        assert_eq!(stats.pending, 0);
    }

    #[test]
    fn tag_formalizability_numeric() {
        let signals = tag_formalizability(
            "what is 140 bpm bar duration",
            "At 140 BPM: 1.714 seconds per bar",
            "e_100",
        );
        assert!(!signals.is_empty());
    }

    #[test]
    fn module_path_resolution() {
        assert!(FunctionModule::Finance.module_path().contains("det_finance"));
        assert!(FunctionModule::Music.module_path().contains("det_music"));
        assert!(FunctionModule::New("crypto".to_string()).module_path().contains("det_crypto"));
    }

    #[test]
    fn infer_module_from_bpm() {
        let m = super::infer_module_from_query("what is the bpm of this track");
        assert_eq!(m, FunctionModule::Music);
    }

    #[test]
    fn operator_rule_proposal_roundtrips_json() {
        let proposal = OperatorRuleProposal {
            id: "orp-001".to_string(),
            rule_id: "bpm-bar-duration".to_string(),
            description: "Calculate bar duration from BPM".to_string(),
            trigger_keywords: vec!["bpm".to_string(), "bar".to_string()],
            semantic_hint: Some("bar duration from tempo".to_string()),
            formula: ProposedFormula::Arithmetic {
                expr: "60 / x * 4".to_string(),
                variables: vec!["x".to_string()],
            },
            confidence: 0.92,
            supporting_episodes: vec!["ep-001".to_string()],
            example_inputs: vec!["what is a bar at 120 bpm".to_string()],
            example_outputs: vec!["2.000 seconds".to_string()],
            proposed_at: Utc::now(),
            status: ProposalStatus::Pending,
        };
        let json = serde_json::to_string(&proposal).unwrap();
        let back: OperatorRuleProposal = serde_json::from_str(&json).unwrap();
        assert_eq!(back.id, "orp-001");
        assert_eq!(back.confidence, 0.92);
    }

    #[test]
    fn proposed_formula_static_roundtrips() {
        let formula = ProposedFormula::Static { response: "hello".to_string() };
        let json = serde_json::to_string(&formula).unwrap();
        let back: ProposedFormula = serde_json::from_str(&json).unwrap();
        match back {
            ProposedFormula::Static { response } => assert_eq!(response, "hello"),
            _ => panic!("expected Static"),
        }
    }

    #[test]
    fn proposed_formula_lookup_roundtrips() {
        let formula = ProposedFormula::Lookup {
            pairs: vec![
                ("C major".to_string(), "C D E F G A B".to_string()),
                ("A minor".to_string(), "A B C D E F G".to_string()),
            ],
        };
        let json = serde_json::to_string(&formula).unwrap();
        let back: ProposedFormula = serde_json::from_str(&json).unwrap();
        match back {
            ProposedFormula::Lookup { pairs } => assert_eq!(pairs.len(), 2),
            _ => panic!("expected Lookup"),
        }
    }
}
